{% set name = "tb-profiler" %}
{% set version = "2.0_BETA" %}
{% set sha256 = "b39a9acfcb3b2ccafcb7a716e7bdb7fcf6f09d892b7567d4461b34591bbe9733" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/jodyphelan/TBProfiler/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pathogen-profiler
    - tqdm
test:
  imports:
    - tbprofiler
  commands:
    - tb-profiler -h
    - tb-profiler test

about:
  home: https://github.com/jodyphelan/TBProfiler
  license: GPL3
  license_file: LICENSE
  summary: TBProfiler tools for Mtb NGS data
