{% set name = "tb-profiler" %}
{% set version = "v2.0_BETA" %}
{% set sha256 = "806dd99d4c1ea820db86f851c99a5503d9b2e57284777f13c1d73c616fb3c730" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/jodyphelan/TBProfiler/archive/{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pathogen-profiler
    - tqdm
test:
  imports:
    - tbprofiler
  commands:
    - tb-profiler -h
    - tb-profiler test

about:
  home: https://github.com/jodyphelan/TBProfiler
  license: GPL3
  license_file: LICENSE
  summary: Microbial assembly pipeline for Illumina paired-end reads
