{% set name = "tb-profiler" %}
{% set version = "0.1" %}
{% set sha256 = "704fd29bb6e87a6cd66302826db195f9e57097a04d8aa8a74f9c8c96d93e8ab2" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/jodyphelan/TBProfiler2/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pathogen-profiler
    - tqdm
test:
  imports:
    - tbprofiler
  commands:
    - tb-profiler -h
    - tb-profiler test

about:
  home: https://github.com/jodyphelan/TBProfiler2
  license: GPL3
  license_file: LICENSE
  summary: Microbial assembly pipeline for Illumina paired-end reads
